### ISSUE TITLE
Problema ao rodar o projeto com Gradle

### ISSUE THREAD

**Issue by andreyferraz** [cami-la/programacao_assistida_por_IA_com_Amazon_CodeWhisperer#2]
Ei Camila, infelizmente não estou conseguindo rodar esse projeto, já tentei diversas formas, e por último estou obtendo esse log:

`PS C:\Users\Andrêy Ferraz\Desktop\Estudos\Bootcamp Cooding the Future - GFT AWS\programacao_assistida_por_IA_com_Amazon_CodeWhisperer-master> gradle build
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> error: invalid source release: 17

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 7s
1 actionable task: 1 executed
PS C:\Users\Andrêy Ferraz\Desktop\Estudos\Bootcamp Cooding the Future - GFT AWS\programacao_assistida_por_IA_com_Amazon_CodeWhisperer-master>`

**Comment by cami-la** [comment]
Oi, @andreyferraz. Tudo certinho?

**error: invalid source release: 17**

Acredito que você não está utilizando o JDK 17 neste projeto, para confirmar segue os passos no IntelliJ:

1. File >> Project Structure

![Screenshot from 2023-08-14 15-47-10](https://github.com/cami-la/programacao_assistida_por_IA_com_Amazon_CodeWhisperer/assets/64323124/6d4215a3-5550-43e1-8bda-9975631648da)

![Screenshot from 2023-08-14 15-43-57](https://github.com/cami-la/programacao_assistida_por_IA_com_Amazon_CodeWhisperer/assets/64323124/65f07186-f534-41e2-981e-d758b267780f)

![Screenshot from 2023-08-14 15-44-21](https://github.com/cami-la/programacao_assistida_por_IA_com_Amazon_CodeWhisperer/assets/64323124/f8a5d128-d8d8-456c-b950-69e8767109f4)

Confirma se o seu está assim.

Caso você não consiga encontrar o erro, podemos tentar na live de hoje à noite. ;)

**Comment by andreyferraz** [comment]
Eu consegui rodar aqui, mais foi uma loucura, obrigada pelas instruções!
